/**
 * Search terms that can be used as a query in the {@link utils/BooksAPI/search}
 * method of the provided API.
 * @see utils/BooksAPI
 * @see {@link https://github.com/udacity/reactnd-project-myreads-starter/blob/master/SEARCH_TERMS.md | 'List of supported search terms'}
 */
export const searchTerms = [
    'Android',
    'Art',
    'Artificial Intelligence',
    'Astronomy',
    'Austen',
    'Baseball',
    'Basketball',
    'Bhagat',
    'Biography',
    'Brief',
    'Business',
    'Camus',
    'Cervantes',
    'Christie',
    'Classics',
    'Comics',
    'Cook',
    'Cricket',
    'Cycling',
    'Desai',
    'Design',
    'Development',
    'Digital Marketing',
    'Drama',
    'Drawing',
    'Dumas',
    'Education',
    'Everything',
    'Fantasy',
    'Film',
    'Finance',
    'First',
    'Fitness',
    'Football',
    'Future',
    'Games',
    'Gandhi',
    'Homer',
    'Horror',
    'Hugo',
    'Ibsen',
    'Journey',
    'Kafka',
    'King',
    'Lahiri',
    'Larsson',
    'Learn',
    'Literary Fiction',
    'Make',
    'Manage',
    'Marquez',
    'Money',
    'Mystery',
    'Negotiate',
    'Painting',
    'Philosophy',
    'Photography',
    'Poetry',
    'Production',
    'Programming',
    'React',
    'Redux',
    'River',
    'Robotics',
    'Rowling',
    'Satire',
    'Science Fiction',
    'Shakespeare',
    'Singh',
    'Swimming',
    'Tale',
    'Thrun',
    'Time',
    'Tolstoy',
    'Travel',
    'Ultimate',
    'Virtual Reality',
    'Web Development',
    'iOS'
 ];
